version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings
        columns:
          - name: room_type
            tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4
          - name: price
            tests:
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "^\\\\$[0-9][0-9\\\\.]+$" #^(shift + ^) indicates thar the regular expression must start with "$"(in this case)

      - name: hosts
        identifier: raw_hosts

      - name: reviews
        identifier: raw_reviews

        loaded_at_field: date  #will check in this field if there is new data
        freshness:
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 24
            period: hour

